### ISSUE TITLE
Train CNN for stock/pct detection

### ISSUE THREAD

**Issue by BigLesbianFox** [sverona/meleedb-segment#1]
[jonascarpay/visor](https://github.com/jonascarpay/visor) does this well, apparently. The network design seems sound enough but right now I can't install LLVM 3.7 on this thing so using it as a drop-in or bootstrap is probably no good.

Given that segmentation already pretty much works it shouldn't be hard to just write a little script to collect data from a terminal and run it on a bunch of sets idly while doing other stuff.

**Comment by sverona** [comment]
Closing this because it's not really descriptive enough

**Comment by BigLesbianFox** [comment]
Closing this because it's not really descriptive
